[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[lib]
name = "url_shortener"
path = "src/lib/lib.rs"

[[bin]]
name = "url-shortener-server"
path = "src/bin/server/main.rs"

[dependencies]
nanoid = "0.4.0"
anyhow = { version = "1.0.94", features = ["default"] }
derive_more = { version = "1.0.0", features = ["from"] }
thiserror = "2.0.8"
url = { version = "2.5.4", features = ["serde"] }
tokio = "1.42.0"
serde = { version = "1.0.216" }
serde_json = "1.0.133"
mongodb = { version = "3.1.1", features = ["rustls-tls"] }
actix-web = "4.9.0"
env_logger = "0.11.5"
reqwest = { version = "0.12.9", features = ["json"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-opentelemetry = "0.28.0"
opentelemetry = { version = "0.27.1" }
opentelemetry-jaeger = "0.22.0"

[dev-dependencies]
mockall = "0.13.0"
testcontainers = "0.23.1"
testcontainers-modules = { version = "0.11.4", features = ["mongo"] }

