[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[lib]
name = "url_shortener"
path = "src/lib/lib.rs"

[[bin]]
name = "url_shortener_server"
path = "src/bin/server/main.rs"

[dependencies]
nanoid = "0.4.0"
anyhow = { version = "1.0.89", features = ["default"] }
derive_more = { version = "1.0.0", features = ["from"] }
thiserror = "1.0.63"
url = { version = "2.5.2", features = ["serde"] }
tokio = "1.40.0"
serde = { version = "1.0.210" }
serde_json = "1.0.128"
futures = "0.3.30"
mongodb = { version = "3.1.0", features = ["rustls-tls"] }
actix-web = "4.9.0"
env_logger = "0.11.5"
reqwest = { version = "0.12.7", features = ["json"] }

[dev-dependencies]
mockall = "0.13.0"
testcontainers = "0.22.0"
testcontainers-modules = { version = "0.10.0", features = ["mongo"] }

