version: '3.8'
name: "url-shortener"

services:

#  url-shortener:
#    build: .
#    image: localhost/url-shortener:latest
#    ports:
#      - "8080:8080"
#    links:
#      - mongodb
#    environment:
#      - MONGO_URI=mongodb://urlShortener:password@mongodb:27017/urlShortenerDb?w=majority

  mongodb:
    image: mongo:5.0.25-nanoserver
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_SHORT_URLS_DB=urlShortenerDb
      - MONGO_SHORT_URLS_DB_USERNAME=urlShortener
      - MONGO_SHORT_URLS_DB_PASSWORD=password
    volumes:
      - ./mongo/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - type: bind
        source: ./mongo/data
        target: /data/db