[workspace]
resolver = "2"
members = [
    "json-parser",
    "url-shortener",
    "web-server"
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.97"
thiserror = "2.0.12"
tracing = "0.1.41"
tokio = { version = "1.44.1", features = ["full"] }