name: "load-balancer"
services:

  server_a:
    build: server/.
    image: localhost/server:latest
    ports:
      - "8081:8081"
    environment:
      - SERVER_NAME=R2D2

  server_b:
    build: server/.
    image: localhost/server:latest
    ports:
      - "8082:8081"
    environment:
      - SERVER_NAME=Chewbacca

  server_c:
    build: server/.
    image: localhost/server:latest
    ports:
      - "8083:8081"
    environment:
      - SERVER_NAME=C3P0

  load-balancer:
    build: load-balancer/.
    image: localhost/load-balancer:latest
    environment:
      - CONFIG_FILE=/load-balancer/configuration/docker.yaml
    ports:
      - "8080:8080"
    links:
      - server_a
      - server_b
      - server_c