name: Security Audit Json Parser
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'json-parser/**/Cargo.toml'
      - 'json-parser/**/Cargo.lock'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rust-toolchain.toml'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
        working-directory: ./json-parser