name: Security Audit Load Balancer
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'load-balancer/**/Cargo.toml'
      - 'load-balancer/**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
        working-directory: ./load-balancer